
version: '3.3'

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind 
      device: /home/tbillon/data/wp
      
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind 
      device: /home/tbillon/data/db

networks:
  inception:
    driver: bridge
 
services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    networks:
       - inception
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    restart: always
    tty: true

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env
    restart: always
    depends_on:
      - mariadb
    tty: true

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    restart: always
    depends_on:
      - wordpress