ALTER USER 'root'@ 'localhost' IDENTIFIED BY 'MYSQL_ROOT_PWD';
CREATE DATABASE WP_DB_NAME;
CREATE USER 'WP_DB_USR'@'%' IDENTIFIED BY 'WP_DB_PWD';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON WP_DB_NAME.* TO 'WP_DB_USR'@'%';
FLUSH PRIVILEGES
QUIT